# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Question.destroy_all
Question.create(id: 1, body: "The mood you were in:", watson: false, interface_name: "mood")
Question.create(id: 2, body: "What you did that day:", watson: false, interface_name: "text_list")
Question.create(id: 3, body: "Who your day involved:", watson: false, interface_name: "text_list")
Question.create(id: 4, body: "The way you described your day:", watson: false, interface_name: "text_list")
Question.create(id: 5, body: "What you were grateful for:", watson: false, interface_name: "text_list")
Question.create(id: 6, body: "What else you had to say:", watson: true, interface_name: "textarea")

moods = ["thoughtful", "curious", "serene", "grateful", "love", "happy", "anxious", "scared", "angry", "bored", "sad", "remorseful"]
User.destroy_all
User.create(email: "present@ti.on", first_name: "Everybody", last_name: "Watching", reset_password_token: "1", password: "123456")
user = User.create(email: "2@email.com", first_name: "2", last_name: "2", reset_password_token: "2", password: "123456")
entry = user.entries.create!()
prompt = entry.prompts.create(question_id: 1)
prompt.answers.create(user_id: user.id, body: moods[0])
prompt.answers.create(user_id: user.id, body: moods[1])
prompt.answers.create(user_id: user.id, body: moods[2])
prompt.answers.create(user_id: user.id, body: moods[3])
prompt.answers.create(user_id: user.id, body: moods[4])
prompt.answers.create(user_id: user.id, body: moods[6])
prompt.answers.create(user_id: user.id, body: moods[7])
prompt.answers.create(user_id: user.id, body: moods[8])
prompt.answers.create(user_id: user.id, body: moods[10])
prompt.answers.create(user_id: user.id, body: moods[11])

user = User.create(email: "3@email.com", first_name: "3", last_name: "3", reset_password_token: "3", password: "123456")
entry = user.entries.create!()
prompt = entry.prompts.create(question_id: 1)
prompt.answers.create(user_id: user.id, body: moods[0])
prompt.answers.create(user_id: user.id, body: moods[1])
prompt.answers.create(user_id: user.id, body: moods[2])
prompt.answers.create(user_id: user.id, body: moods[4])
prompt.answers.create(user_id: user.id, body: moods[6])
prompt.answers.create(user_id: user.id, body: moods[7])
prompt.answers.create(user_id: user.id, body: moods[8])
prompt.answers.create(user_id: user.id, body: moods[9])
prompt.answers.create(user_id: user.id, body: moods[10])
prompt.answers.create(user_id: user.id, body: moods[11])

user = User.create(email: "4@email.com", first_name: "4", last_name: "4", reset_password_token: "4", password: "123456")
entry = user.entries.create!()
prompt = entry.prompts.create(question_id: 1)
prompt.answers.create(user_id: user.id, body: moods[0])
prompt.answers.create(user_id: user.id, body: moods[1])
prompt.answers.create(user_id: user.id, body: moods[2])
prompt.answers.create(user_id: user.id, body: moods[3])
prompt.answers.create(user_id: user.id, body: moods[4])
prompt.answers.create(user_id: user.id, body: moods[5])
prompt.answers.create(user_id: user.id, body: moods[10])
prompt.answers.create(user_id: user.id, body: moods[11])

user = User.create(email: "5@email.com", first_name: "5", last_name: "5", reset_password_token: "5", password: "123456")
entry = user.entries.create!()
prompt = entry.prompts.create(question_id: 1)
prompt.answers.create(user_id: user.id, body: moods[0])
prompt.answers.create(user_id: user.id, body: moods[1])
prompt.answers.create(user_id: user.id, body: moods[2])
prompt.answers.create(user_id: user.id, body: moods[3])
prompt.answers.create(user_id: user.id, body: moods[4])
prompt.answers.create(user_id: user.id, body: moods[5])
prompt.answers.create(user_id: user.id, body: moods[6])
prompt.answers.create(user_id: user.id, body: moods[10])
prompt.answers.create(user_id: user.id, body: moods[11])

user = User.create(email: "6@email.com", first_name: "6", last_name: "6", reset_password_token: "6", password: "123456")
entry = user.entries.create!()
prompt = entry.prompts.create(question_id: 1)
prompt.answers.create(user_id: user.id, body: moods[0])
prompt.answers.create(user_id: user.id, body: moods[1])
prompt.answers.create(user_id: user.id, body: moods[2])
prompt.answers.create(user_id: user.id, body: moods[3])
prompt.answers.create(user_id: user.id, body: moods[4])
prompt.answers.create(user_id: user.id, body: moods[6])
prompt.answers.create(user_id: user.id, body: moods[8])
prompt.answers.create(user_id: user.id, body: moods[9])
prompt.answers.create(user_id: user.id, body: moods[10])
prompt.answers.create(user_id: user.id, body: moods[11])

user = User.create(email: "7@email.com", first_name: "7", last_name: "7", reset_password_token: "7", password: "123456")
entry = user.entries.create!()
prompt = entry.prompts.create(question_id: 1)
prompt.answers.create(user_id: user.id, body: moods[0])
prompt.answers.create(user_id: user.id, body: moods[1])
prompt.answers.create(user_id: user.id, body: moods[2])
prompt.answers.create(user_id: user.id, body: moods[3])
prompt.answers.create(user_id: user.id, body: moods[4])
prompt.answers.create(user_id: user.id, body: moods[5])
prompt.answers.create(user_id: user.id, body: moods[6])
prompt.answers.create(user_id: user.id, body: moods[7])
prompt.answers.create(user_id: user.id, body: moods[11])

user = User.create(email: "8@email.com", first_name: "8", last_name: "8", reset_password_token: "8", password: "123456")
entry = user.entries.create!()
prompt = entry.prompts.create(question_id: 1)
prompt.answers.create(user_id: user.id, body: moods[0])
prompt.answers.create(user_id: user.id, body: moods[1])
prompt.answers.create(user_id: user.id, body: moods[2])
prompt.answers.create(user_id: user.id, body: moods[3])
prompt.answers.create(user_id: user.id, body: moods[4])
prompt.answers.create(user_id: user.id, body: moods[5])
prompt.answers.create(user_id: user.id, body: moods[6])
prompt.answers.create(user_id: user.id, body: moods[7])
prompt.answers.create(user_id: user.id, body: moods[8])
prompt.answers.create(user_id: user.id, body: moods[9])
prompt.answers.create(user_id: user.id, body: moods[10])
prompt.answers.create(user_id: user.id, body: moods[11])

user = User.first
entry = user.entries.create!()
prompt = entry.prompts.create(question_id: 1)
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,01,01))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,01,02))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,01,03))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,01,04))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,01,05))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,01,06))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,01,07))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,01,8))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,01,8))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,01,10))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,01,11))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,01,12))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,01,13))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,01,14))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,01,15))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,01,16))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,01,17))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,01,18))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,01,19))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,01,20))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,01,21))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,01,22))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,01,23))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,01,24))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,01,25))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,01,26))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,01,27))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,01,28))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,01,29))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,01,30))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,01,31))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,02,01))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,02,02))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,02,03))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,02,04))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,02,05))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,02,06))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,02,07))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,02,8))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,02,8))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,02,10))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,02,11))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,02,12))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,02,13))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,02,14))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,02,15))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,02,16))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,02,17))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,02,18))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,02,19))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,02,20))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,02,21))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,02,22))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,02,23))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,02,24))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,02,25))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,02,26))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,02,27))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,02,28))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,03,01))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,03,02))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,03,03))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,03,04))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,03,05))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,03,06))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,03,07))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,03,8))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,03,8))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,03,10))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,03,11))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,03,12))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,03,13))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,03,14))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,03,15))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,03,16))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,03,17))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,03,18))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,03,19))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,03,20))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,03,21))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,03,22))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,03,23))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,03,24))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,03,25))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,03,26))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,03,27))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,03,28))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,03,29))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,03,30))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,03,31))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,04,01))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,04,02))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,04,03))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,04,04))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,04,05))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,04,06))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,04,07))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,04,8))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,04,8))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,04,10))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,04,11))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,04,12))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,04,13))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,04,14))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,04,15))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,04,16))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,04,17))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,04,18))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,04,19))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,04,20))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,04,21))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,04,22))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,04,23))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,04,24))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,04,25))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,04,26))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,04,27))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,04,28))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,04,29))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,04,30))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,05,01))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,05,02))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,05,03))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,05,04))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,05,05))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,05,06))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,05,07))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,05,8))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,05,8))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,05,10))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,05,11))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,05,12))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,05,13))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,05,14))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,05,15))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,05,16))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,05,17))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,05,18))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,05,19))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,05,20))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,05,21))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,05,22))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,05,23))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,05,24))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,05,25))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,05,26))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,05,27))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,05,28))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,05,29))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,05,30))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,05,31))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,06,01))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,06,02))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,06,03))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,06,04))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,06,05))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,06,06))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,06,07))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,06,8))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,06,8))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,06,10))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,06,11))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,06,12))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,06,13))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,06,14))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,06,15))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,06,16))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,06,17))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,06,18))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,06,19))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,06,20))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,06,21))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,06,22))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,06,23))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,06,24))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,06,25))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,06,26))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,06,27))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,06,28))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,06,29))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,06,30))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,07,01))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,07,02))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,07,03))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,07,04))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,07,05))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,07,06))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,07,07))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,07,8))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,07,8))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,07,10))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,07,11))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,07,12))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,07,13))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,07,14))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,07,15))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,07,16))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,07,17))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,07,18))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,07,19))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,07,20))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,07,21))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,07,22))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,07,23))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,07,24))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,07,25))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,07,26))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,07,27))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,07,28))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,07,29))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,07,30))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,07,31))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,8,01))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,8,02))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,8,03))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,8,04))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,8,05))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,8,06))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,8,07))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,8,8))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,8,8))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,8,10))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,8,11))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,8,12))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,8,13))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,8,14))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,8,15))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,8,16))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,8,17))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,8,18))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,8,19))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,8,20))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,8,21))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,8,22))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,8,23))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,8,24))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,8,25))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,8,26))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,8,27))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,8,28))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,8,29))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,8,30))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,8,31))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,8,01))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,8,02))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,8,03))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,8,04))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,8,05))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,8,06))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,8,07))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,8,8))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,8,8))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,8,10))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,8,11))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,8,12))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,8,13))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,8,14))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,8,15))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,8,16))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,8,17))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,8,18))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,8,19))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,8,20))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,8,21))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,8,22))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,8,23))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,8,24))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,8,25))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,8,26))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,8,27))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,8,28))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,8,29))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,8,30))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,10,01))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,10,02))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,10,03))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,10,04))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,10,05))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,10,06))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,10,07))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,10,8))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,10,8))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,10,10))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,10,11))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,10,12))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,10,13))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,10,14))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,10,15))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,10,16))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,10,17))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,10,18))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,10,19))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,10,20))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,10,21))
prompt.answers.create(user_id: user.id, body: "serene", created_at: Date.new(2018,10,22))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,10,23))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,10,24))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,10,25))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,10,26))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,10,27))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,10,28))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,10,29))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,10,30))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,10,31))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,11,01))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,11,02))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,11,03))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,11,04))
prompt.answers.create(user_id: user.id, body: "sad", created_at: Date.new(2018,11,05))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,11,06))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,11,07))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,11,8))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,11,8))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,11,10))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,11,11))
prompt.answers.create(user_id: user.id, body: "loving", created_at: Date.new(2018,11,12))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,11,13))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,11,14))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,11,15))
prompt.answers.create(user_id: user.id, body: "angry", created_at: Date.new(2018,11,16))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,11,17))
prompt.answers.create(user_id: user.id, body: "happy", created_at: Date.new(2018,11,18))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,11,19))
prompt.answers.create(user_id: user.id, body: "thoughtful", created_at: Date.new(2018,11,20))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,11,21))
prompt.answers.create(user_id: user.id, body: "anxious", created_at: Date.new(2018,11,22))
prompt.answers.create(user_id: user.id, body: "scared", created_at: Date.new(2018,11,23))
prompt.answers.create(user_id: user.id, body: "grateful", created_at: Date.new(2018,11,24))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,11,25))
prompt.answers.create(user_id: user.id, body: "curious", created_at: Date.new(2018,11,26))
prompt.answers.create(user_id: user.id, body: "bored", created_at: Date.new(2018,11,27))
prompt.answers.create(user_id: user.id, body: "remorseful", created_at: Date.new(2018,11,28))
